name: Automation Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [web, api]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable chromium-browser

      - name: Grant permission
        run: chmod +x gradlew

      - name: Run ${{ matrix.test-type }} Test
        run: ./gradlew ${{ matrix.test-type }}Test
        continue-on-error: true

      - name: Upload ${{ matrix.test-type }} Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.test-type }}-test-reports
          path: |
            reports/${{ matrix.test-type }}-cucumber-report.html
            reports/${{ matrix.test-type }}-cucumber-report.json
          retention-days: 30
          if-no-files-found: warn

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/${{ matrix.test-type }}-cucumber-report.json
          check_name: ${{ matrix.test-type }} Test Results
        continue-on-error: true
